### ISSUE TITLE
issue-1-user-can-document-and-rate-whiskies

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/ajax-project#1]
## 💰 Motivation

Whiskey enthusiasts will want to keep track of different whiskies they have tried and rank them throughout his or her life.

## 📐 Plan

Create a responsive form that allows users to store the name of the whiskey, distillery, date they tried it on, age, tasting profile (sweet or peaty, smooth or intense, and tasting notes), and a final score.

## 🖼️ Wireframes
[User can create entry mobile] 
<img width="338" alt="Screen Shot 2021-11-16 at 4 37 41 PM" src="https://user-images.githubusercontent.com/72685552/142088318-a4e4e35c-e888-478b-b6b0-8f13849da181.png">

[User can create entry desktop] 
<img width="595" alt="Screen Shot 2021-11-16 at 4 39 23 PM" src="https://user-images.githubusercontent.com/72685552/142088422-e5b7a7c8-bb6e-4004-a489-8b5cadfc8172.png">

## ✅ Task List

- [x] Create a background header img similar to the ones in the wireframes.
  - [x] Within the img create a header called “The Whisk[e]y Lounge.” This will remain constant through entire application.
- [x] Add a ‘div[data-view = “entry-form” to HTML
- [x] Add a form for creating a journal entry form to the ‘div[data-view=”entry-form”]
- [x] Ensure that the form looks nice on both mobile and desktop sized screens
- [x] Make whisky name, distillery, date, age, and final score required entries
- [x] Listen for ‘submit’ events on the journal entry form and:
  - [x] Put the form’s input values into a new object.
  - [x] Record the line graph toggles inputs
  - [x] Add the `nextEntryId` to the object.
  - [x] Increment the `nextEntryId` on the data model.
  - [x] Prepend the new object to the entries in the data model.
  - [x] Reset the form inputs.
- [x] Verify the  new entries are saved to local storage along with the ret of the data model on page reload
- [x] Verify each new entry receives an incrementing ‘entryId’.
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in incognito
- [x] Fix all outstanding errors
