### ISSUE TITLE
issue-2-user-can-view-whiskey-logs

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/ajax-project#2]
## 💰 Motivation

Once a user records a whiskey, they may want to refer back to it in the future.

## 📐 Plan

Display a user summary of a user’s whiskey entries by date so that they are able to keep track of what they have tried.

## 🖼️ Wireframes
[User No Logs Mobile View]
<img width="332" alt="Screen Shot 2021-11-16 at 4 58 18 PM" src="https://user-images.githubusercontent.com/72685552/142090024-8bd7093e-967c-4c62-8bdb-fb0907f68778.png">
[User Logs Mobile View]
<img width="328" alt="Screen Shot 2021-11-16 at 4 58 58 PM" src="https://user-images.githubusercontent.com/72685552/142090076-03097ca6-3cee-494e-b010-1752ba9eb9d6.png">
[User No Logs Desktop View]
<img width="590" alt="Screen Shot 2021-11-16 at 5 00 31 PM" src="https://user-images.githubusercontent.com/72685552/142090224-6f7e08dc-0724-4b6a-bd96-d49324fab97a.png">
[User Logs Desktop View]
<img width="592" alt="Screen Shot 2021-11-16 at 5 03 33 PM" src="https://user-images.githubusercontent.com/72685552/142090561-119cc392-5540-483d-a697-ae27ba1f58cd.png">

## ✅ Task List

- [x] Add a sibling ‘div[data-view=”Entries”]’ to the HTML.
- [x] Add an empty unordered list to the ‘div[data-view=”entries”]’ element in HTML.
- [x] Add some dummy entries to ensure the list in HTML matches the wireframes.
- [x] Check that entries list looks good on both mobile and desktop screens
- [x] Define a function that will take a single entry object and returns a DOM tree that matches one of the examples
- [x] Use a loop to create a DOM tree for each journal entry in the data model and append it to the page when the ‘DOMContentLoaded’ event is fired.
- [x] Remove example HTML entries once user’s entries successfully append to the DOM
- [x] Add a navigation item for entries to the top right of the page for Logs.
- [x] Add an anchor to entries that show entry form.
- [x] Add an anchor to the “The Whisk[e]y Lounge” logo on the top left. This will be a link back to creating a new entry.
- [x] Ensure that submitting a new entry creates a new DOM tree for it and adds it to the page.
- [x] If there are no entries ensure that the message appears on the screen.
- [x] Ensure that submitting a new journal entry automatically shows the ‘entries’ view without reloading the page. Use prepend method for this.
- [x] Ensure refreshing pages shows the same view before refreshing. 
- [x] Clean up all unnecessary CSS styling.
- [x] Test all functionality again in incognito.
- [x] Fix all outstanding errors

**Comment by jonathanymatsuda** [comment]
Last Todos: See if you can style sliders in entries (input:disabled)
Fix Line break later
