### ISSUE TITLE
issue-3-user-can-make-updates

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/ajax-project#3]
## 💰 Motivation

User’s can either fix their mistakes or if their opinion has changed over time they will be able to make edits.

## 📐 Plan

Allow users to select an existing log and edit it with the existing information in the form.

## 🖼️ Wireframes
[Users can make edits - edit button - mobile]
<img width="339" alt="Screen Shot 2021-11-16 at 5 17 30 PM" src="https://user-images.githubusercontent.com/72685552/142091632-0fa5b24d-614f-4b65-95ee-ee4635505813.png">
[Users can make edits in edit mode - mobile]
<img width="333" alt="Screen Shot 2021-11-16 at 5 20 03 PM" src="https://user-images.githubusercontent.com/72685552/142091836-4b4316d3-161e-4992-9de9-53f7a452aedd.png">
[Users can make edits - edit button - desktop]
<img width="587" alt="Screen Shot 2021-11-16 at 5 21 10 PM" src="https://user-images.githubusercontent.com/72685552/142091929-5ed874c6-eb04-4a1f-8f80-2d8b34029476.png">
[Users can make edits in edit mode - dekstop]
<img width="586" alt="Screen Shot 2021-11-16 at 5 23 19 PM" src="https://user-images.githubusercontent.com/72685552/142092090-e0676716-4d23-492f-8fb7-5b68fb1123d6.png">

## ✅ Task List
- [x] Update entry rendering function to include the edit icon for each entry box.
- [x] Ensure that each entry is distinguishable by giving it a ‘data-entry-id’ attribute.
- [x] Listen for clicks on the parent element of all rendered entries.
- [x] Show entry form the edit icon was clicked.
- [x] Find matching entry object in data model and assign it to the data model’s ‘editing’ property if the edit icon was clicked.
- [x] Pre-populate entry form with the clicked entry’s values from the object in the data model.
- [x] Update entry form’s submit handler function to conditionally update the existing one.
- [x] Update entry form’s submit handler function to conditionally replace the existing one.
- [x] Clean up all unnecessary CSS styling.
- [x] Test all functionality again in incognito.
- [x] Fix all outstanding errors
