### ISSUE TITLE
issue-4-user-can-search-distilleries

### ISSUE THREAD

**Issue by jonathanymatsuda** [jonathanymatsuda/ajax-project#4]
## 💰 Motivation

User’s are able to explore different distilleries and track information like the location, the rating, and average sales price from the auctions.

## 📐 Plan

Allow users to click on the explore tag on the top right and then the distilleries icon with a view of all different distilleries from the WhiskyHunter API.

## 🖼️ Wireframes
[Whiskey explore page - link to distilleries - mobile]
<img width="325" alt="Screen Shot 2021-11-16 at 5 33 46 PM" src="https://user-images.githubusercontent.com/72685552/142092959-4944b92b-f48c-452a-861c-c70abc68a7da.png">
[Distillery page - mobile]
<img width="324" alt="Screen Shot 2021-11-16 at 5 36 31 PM" src="https://user-images.githubusercontent.com/72685552/142093247-a871b654-1161-4fff-a9de-633b66bad496.png">
[Whiskey explore page - link to distilleries - mobile]
<img width="591" alt="Screen Shot 2021-11-16 at 5 38 02 PM" src="https://user-images.githubusercontent.com/72685552/142093375-94f4a9cc-fff9-4b99-834c-2b2a03139a4d.png">
[Distillery page - desktop]
<img width="585" alt="Screen Shot 2021-11-16 at 5 39 49 PM" src="https://user-images.githubusercontent.com/72685552/142093553-c2ac90bd-35ef-451f-906e-8df28effe834.png">
## ✅ Task List
- [x] Add a sibling ‘div[data-view=”distilleries-view”]’ in HTML.
- [x] Add an empty unordered list to the ‘div[data-view=”distilleries-view”]’ in HTML.
- [x] Create one dummy distillery panel to ensure formatting looks good on both mobile and desktop
- [x] Query the DOM for the ‘#distilleries-list’ element (Be sure to create it first!)
- [x] Make a function that:
  - [x] Creates a new XMLHttpReqest Object for distilleries_info (https://whiskyhunter.net/api/distilleries_info/)
  - [x] Opens the request
  - [x] Sets responseType to JSON
  - [x] Adds a load event listener to obtain: ‘country’, ‘whiskeybase_rating’, and ‘whiskey_base’ votes
  - [x] Appends the information to the ‘#distilleries-list’ element
- [ ] Make another function that:
  - [ ] Creates a new XMLHttpRequest object for distillery_data based off slug name (https://whiskyhunter.net/api/distillery_data/abbeyhill/)
  - [ ] Opens the request
  - [ ] Sets response Type to JSON
  - [ ] Adds a load event listener to obtain: ‘dt’ and ‘winning_bid_max”
  - [ ] Ensure that you only get from 2021 and that you take the average of the ‘winning_bid_max’ to get the Average Sales Price for the year.
  - [ ] Appends the information to the ‘#distilleries-list’ element
- [x] Create a search bar so users will be able to search for specific distilleries if needed
- [x] Add a navigation item for entries to the top right of the page for Explore
- [x] Add an anchor to the Explore that will show the explore page
- [ ] Create a Distilleries icon on the explore page
- [ ] Add an anchor to the Distilleries icon that will show the distillery view
- [ ] Clean up all unnecessary CSS styling.
- [ ] Test all functionality again in incognito.
- [ ] Fix all outstanding errors

**Comment by jonathanymatsuda** [comment]
Figure out distillery dom issue - how to get two of them in one row
Also might change average sales price to number of whiskies
